import Image from "next/image";
import { Radar, ScanLine, Network, Fingerprint, Check, Shield } from "lucide-react";
import RequestForm from "@/components/request-form";
const solutions = [
  { number: "01", icon: Radar, title: "AI destekli tehdit analizi", description: "Dağınık tehdit sinyallerini anlamlı istihbarata dönüştürün. Güvenlik ekibinizin dikkatini kurumunuz için önemli risklere yönlendirin.", tag: "THREAT INTELLIGENCE" },
  { number: "02", icon: ScanLine, title: "Attack Surface Management", description: "İnternete açık dijital varlıklarınızı görünür kılın. Unutulmuş sistemleri ve saldırganların kullanabileceği açıklıkları tespit edin.", tag: "EXTERNAL EXPOSURE" },
  { number: "03", icon: Network, title: "Güvenlik olaylarının korelasyonu", description: "Tek başına anlamsız görünen olaylar arasındaki bağlantıları ortaya çıkarın. Olayın bağlamını anlayın, müdahaleyi önceliklendirin.", tag: "SECURITY OPERATIONS" },
  { number: "04", icon: Fingerprint, title: "Dijital varlık ve risk haritalama", description: "Varlıklarınızı, birbirleriyle ilişkilerini ve işiniz için taşıdıkları riski aynı çerçevede değerlendirin. Önce neyi koruyacağınızı bilin.", tag: "RISK VISIBILITY" },
];
export default function Home() {
  return <>
    <a className="skip-link" href="#main">İçeriğe geç</a>
    <header className="site-header container"><a className="brand" href="#" aria-label="VANTA ana sayfa"><span className="brand-mark" aria-hidden="true">V</span><span>VANTA<span className="brand-sub">CYBER INTELLIGENCE</span></span></a><nav aria-label="Ana navigasyon"><a href="#approach">Yaklaşımımız</a><a href="#solutions">Hizmetler</a></nav><a href="#contact" className="button header-button">İletişime geç</a></header>
    <main id="main">
      <section className="hero container" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span className="small-rule" />TEHDİTLERİN BİR ADIM ÖNÜNDE</p><h1 id="hero-title">Tehdidi, sizi<br />bulmadan <span>görün.</span></h1><p className="hero-description">Güvenlik ekipleri için siber tehdit istihbaratı, saldırı yüzeyi analizi ve yapay zekâ destekli güvenlik operasyonları. Daha fazla sinyal değil, daha net kararlar.</p><div className="hero-actions"><a href="#contact" className="button primary">Güvenlik ihtiyacınızı konuşalım</a><a href="#solutions" className="text-link">Hizmetleri keşfet</a></div><p className="slogan">“See the threats before they see you.”</p></div><div className="hero-visual"><Image src="/vanta-hero.webp" alt="" width={1254} height={1254} priority unoptimized className="hero-art" /><div className="visual-caption"><span className="caption-line" /><p>Önce görünürlük.<br /><strong>Sonra doğru karar.</strong></p></div><span className="visual-coordinate">V / INTELLIGENCE LAYER</span></div></section>
      <div className="principles container"><span><Shield size={18} aria-hidden="true" />Kurumunuza özel istihbarat</span><span><Check size={18} aria-hidden="true" />Risk odaklı önceliklendirme</span><span><Network size={18} aria-hidden="true" />Bağlantılı güvenlik operasyonları</span></div>
      <section id="approach" className="approach container section" aria-labelledby="approach-title"><div><p className="eyebrow">01 / YAKLAŞIMIMIZ</p><h2 id="approach-title">Görmediğiniz riski<br />yönetemezsiniz.</h2></div><div className="approach-copy"><p>Saldırı yüzeyiniz büyürken güvenlik sinyalleri de çoğalıyor. Her uyarı aynı önemi taşımıyor; ekibinizin zamanı ise sınırlı.</p><p>VANTA, güvenlik ve BT ekiplerinin dijital varlıklarını anlamasına, tehditleri bağlamıyla değerlendirmesine ve en kritik risklere odaklanmasına yardımcı olur.</p><span className="audience">Güvenlik liderleri · SOC ekipleri · BT ekipleri</span></div></section>
      <section id="solutions" className="solutions container section" aria-labelledby="solutions-title"><div className="section-heading"><div><p className="eyebrow">02 / HİZMETLERİMİZ</p><h2 id="solutions-title">Dört uzmanlık.<br /><span className="muted-heading">Tek bir güvenlik perspektifi.</span></h2></div><p>Varlıktan tehdide, sinyalden karara.<br />İhtiyacınız olan noktadan başlayın.</p></div><div className="solution-grid">{solutions.map(({ number, icon: Icon, title, description, tag }) => <article className="solution-card" key={number}><div className="card-top"><Icon size={30} strokeWidth={1.25} aria-hidden="true" /><span>{number}</span></div><h3>{title}</h3><p>{description}</p><span className="card-tag">{tag}</span></article>)}</div></section>
      <section className="process container section" aria-labelledby="process-title"><div><p className="eyebrow">03 / NASIL BAŞLARIZ?</p><h2 id="process-title">Doğru sorularla<br />başlayan güvenlik.</h2></div><ol className="process-steps"><li><span>01</span><div><h3>İhtiyacınızı dinleriz</h3><p>Korunacak varlıkları, mevcut yapıyı ve güvenlik önceliklerinizi belirleriz.</p></div></li><li><span>02</span><div><h3>Riski anlamlandırırız</h3><p>İlgili hizmet kapsamında tehditleri ve dışa açık alanları değerlendiririz.</p></div></li><li><span>03</span><div><h3>Bir yol haritası çıkarırız</h3><p>Bulguları uygulanabilir önceliklere ve güvenlik kararlarına dönüştürürüz.</p></div></li></ol></section>
      <section id="contact" className="contact-section" aria-labelledby="contact-title"><div className="contact container"><div className="contact-copy"><p className="eyebrow">04 / BİRLİKTE BAŞLAYALIM</p><h2 id="contact-title">Güvenlik<br />gündeminizi<br /><span>konuşalım.</span></h2><p>İster saldırı yüzeyinizi görmek, ister tehditleri daha iyi anlamak isteyin. İhtiyacınızı paylaşın, uygun yaklaşımı değerlendirelim.</p><div className="contact-detail"><Shield size={22} aria-hidden="true" /><span>Yalnızca ihtiyacınızı paylaşmanız yeterli.<br />Teknik erişim bilgisi istemiyoruz.</span></div></div><RequestForm /></div></section>
    </main><footer className="site-footer container"><a className="brand footer-brand" href="#" aria-label="VANTA sayfa başına dön"><span className="brand-mark" aria-hidden="true">V</span>VANTA</a><p>See the threats before they see you.</p><span>© 2026 VANTA · Kurgusal hizmet</span></footer>
  </>;
}